server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ztf?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com:
      gavin:
        sh: INFO

mybatis:
  mapper-locations: classpath:mapper/*.xml